import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';
import { spacing } from '../theme/spacing';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, padding: spacing.lg, gap: spacing.md },
  title: { color: colors.text, fontWeight: '800', fontSize: 18 },
  albumCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: spacing.lg,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  imageWrap: {
    alignSelf: 'center',
    width: 80, height: 80, borderRadius: 40, backgroundColor: colors.surface,
    alignItems: 'center', justifyContent: 'center', marginBottom: spacing.sm, overflow: 'hidden',
  },
  image: { width: '100%', height: '100%' },
  albumTitle: { color: colors.text, textAlign: 'center', fontWeight: '700', marginBottom: spacing.sm },
  subTitle: { color: colors.muted, marginTop: spacing.xs, marginBottom: spacing.xs },
  groupsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  groupChip: {
    backgroundColor: colors.surface,
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
  },
  groupChipSelected: { backgroundColor: colors.primaryLight, borderColor: colors.primary },
  groupText: { color: colors.text },
  deleteBtn: {
    marginTop: spacing.md,
    backgroundColor: '#ef4444',
    borderRadius: 14,
    paddingVertical: spacing.md,
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
  },
  deleteText: { color: '#fff', fontWeight: '700' },
  closeBtn: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  closeText: { color: '#fff', fontWeight: '700' },
sharedRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 },
sharedLabel: { fontSize: 16, fontWeight: '600' },
contributorsBox: { marginTop: 12 },
sectionTitle: { fontSize: 14, fontWeight: '600', marginBottom: 8 },
chipsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
chip: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 16, borderWidth: 1, borderColor: '#ccc' },
chipSelected: { backgroundColor: '#e8f0ff', borderColor: '#6a9cff' },
chipText: { fontSize: 14 },
chipTextSelected: { fontWeight: '700' },
btnDisabled: { opacity: 0.5 },
// NEW
ownerRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
ownerBadge: { borderRadius: 12, paddingVertical: 4, paddingHorizontal: 8, backgroundColor: '#eef2ff' },
ownerBadgeText: { fontSize: 12, fontWeight: '700' },

sectionTitle: { fontSize: 14, fontWeight: '700', marginTop: 8, marginBottom: 6 },
smallLabel: { fontSize: 12, opacity: 0.8, marginBottom: 6 },

chipsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
chip: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 16, borderWidth: 1, borderColor: '#ccc' },
chipSelected: { backgroundColor: '#e8f0ff', borderColor: '#6a9cff' },
chipText: { fontSize: 14 },
chipTextSelected: { fontWeight: '700' },

btnPrimary: { paddingVertical: 12, alignItems: 'center', borderRadius: 12, backgroundColor: '#1f6feb', marginTop: 8 },
btnPrimaryText: { color: '#fff', fontWeight: '700' },
btnSecondary: { paddingVertical: 12, alignItems: 'center', borderRadius: 12, backgroundColor: '#f1f3f5', marginTop: 8 },
btnSecondaryText: { fontWeight: '700' },
btnDisabled: { opacity: 0.5 },

});
